#!/usr/bin/env bash

# Build the package for e2e tests
scripts/build &&

# Build typescript files in dist-tsc/
tsc -p tsconfig.spec.json &&

# Copy
# - non typescript files on src/
# - the typescript build on dist-tsc/
# to dist-spec/
copyfiles --up=1 "dist-tsc/**/*" "src/**/!(*.ts)" dist-spec &&

# Run tests with jasmine
scripts/jasmine &&

# Clean the build
rimraf dist-tsc dist-spec
