# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to NPM

on:
  push:
    branches: [master, dev, '*']
  create:
    tags: ['v*.*.*', '*']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm run prepublishOnly
      - run: echo "${{ toJson(github.event) }}"

      - if: github.event.ref_type == 'branch' && github.event.ref == 'dev'
        run: NPM_TAG="alpha"

      - if: github.event.ref_type == 'branch' && github.event.ref == 'feature/20'
        run: NPM_TAG="testing"

      - run: echo "unchecked $(NPM_TAG)"

      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     tag: alpha
